# Introduction to Python

Python is a general-purpose interpreted, interactive, object-oriented, and high-level programming language.
Portable,
Extendable, ...


In [ ]:
print('Hello World!')

Hello World!


In [ ]:
if True:
  print('True')
else:
  print('False')

True


**Function in python**

In [ ]:
def printinfo(name, age):
  print('Name :',name)
  print('Age :',age)
  return

printinfo(age = 50, name = 'Dada')

Name : Dada
Age : 50


**Class in Python**

In [ ]:
class Employee():
  empcount = 0

  def __init__(self, name, salary):
    self.name = name
    self.salary = salary
    Employee.empcount += 1
  
  def displaycount(self):
    print(f'Total Employee : {Employee.empcount}')

  def displayemployee(self):
    print('Name: ',self.name,'salary:',self.salary)


emp1 = Employee('Zara', 2000)
emp2 = Employee('Manni', 3000)

emp1.displayemployee()
emp2.displayemployee()

emp2.displaycount()

Name:  Zara salary: 2000
Name:  Manni salary: 3000
Total Employee : 2


# Data Types

1. Numbers
2. String
3. List
4. Tuple
5. Dictionary

**1. Number** --> Number data types stores numeric values and
 are immutable (changing the values result in new allocation  of object.)


1.   int
2.   float
3.   complex




In [ ]:
a = 10
b = 4

print(f'Data type of a : {type(a)}')  #Print the data type

#Addition
c = a + b
print(f'Addition of {a} and {b}: {c}')

#Substraction
d = a - b
print(f'Substraction of {a} and {b}: {d}')

#Multiplication
e = a * b
print(f'Multiplication of {a} and {b}: {e}')

#Division
f = a / b
print(f'Division of {a} and {b}: {f}')

#Exponent
g = a ** b
print(f'Exponent of {a} and {b}: {g}')

#Float data type
print(type(f))  #Print the data type

#Complex data type

num1 = 1 + 5j
num2 = 2 + 3j

print(f'Data type of num1 : {type(num1)}')  #Print the data type

c_add = num1 + num2
print(f'Addition of {num1} and {num2}: {c_add}')

print(f'Data type of c_add : {type(c_add)}')  #Print the data type


Data type of a : <class 'int'>
Addition of 10 and 4: 14
Substraction of 10 and 4: 6
Multiplication of 10 and 4: 40
Division of 10 and 4: 2.5
Exponent of 10 and 4: 10000
<class 'float'>
Data type of num1 : <class 'complex'>
Addition of (1+5j) and (2+3j): (3+8j)
Data type of c_add : <class 'complex'>


**2. String** --> String are sequence of bytes. It accepts single, double and triple quotes to denote string literals.

In [ ]:
word = 'words'
sentence = "This is a sentence"

print(word)

a = 'hello'
b = 'world'
print(a+b)


words
helloworld


**3. List** --> List contains items seperated by commas and enclosed within square barcket.

In [ ]:
mylist = [3,5,4,0,'hello']
print(f'mylist: {mylist} and data type : {type(mylist)}')

newlist1 = [3,[5,4,0,],'hello',[7,4,1]]

print(f'First element of newlist1 : {newlist1[0]}') #print the first element of the list
print(f'Last element of newlist1 : {newlist1[-1]}') #print the last element of the list

#Slice Operator

print(f'First three element of newlist1 : {newlist1[0:3]}')    #inclusive of start index and exclusive of end index

print(f'First three element of newlist1 with 2 steps : {newlist1[0:4:2]}')   #behaves as [start : stop : step]

print(f'Reverse the element of newlist1 : {newlist1[ : :-1]}')   #Reverse the element of list


# Comaparing list

a = [1,2,3,4]
b = [1,2,3,4]

print(a==b)

print(f'Length of a : {len(a)}')
print(f'Max value of a : {max(a)}')
print(f'Min value of a : {min(a)}')

mylist: [3, 5, 4, 0, 'hello'] and data type : <class 'list'>
First element of newlist1 : 3
Last element of newlist1 : [7, 4, 1]
First three element of newlist1 : [3, [5, 4, 0], 'hello']
First three element of newlist1 with 2 steps : [3, 'hello']
Reverse the element of newlist1 : [[7, 4, 1], 'hello', [5, 4, 0], 3]
True
Length of a : 4
Max value of a : 4
Min value of a : 1


**4. Tuple** --> Immutable list, it is a read-only and does not change. And defined using round brackets.

In [ ]:
mytuple = (3,5,4,0,'hello')
print(f'mytuple: {mytuple} and data type : {type(mytuple)}')

mytuple1 = [3,[5,4,0,],'hello',[7,4,1]]

print(f'First element of mytuple : {mytuple[0]}') #print the first element of the tuple
print(f'Last element of mytuple : {mytuple[-1]}') #print the last element of the tuple

#Slice

print(f'First three element of mytuple1 : {mytuple1[0:3]}')    #inclusive of start index and exclusive of end index
print(f'First three element of mytuple1 with 2 steps : {mytuple1[0:4:2]}')   #behaves as [start : stop : step]

print(f'mytuple 2 times : {mytuple * 2}')

mytuple: (3, 5, 4, 0, 'hello') and data type : <class 'tuple'>
First element of mytuple : 3
Last element of mytuple : hello
First three element of mytuple1 : [3, [5, 4, 0], 'hello']
First three element of mytuple1 with 2 steps : [3, 'hello']
mytuple 2 time : (3, 5, 4, 0, 'hello', 3, 5, 4, 0, 'hello')


**5. Dictionary** --> Dictionaries are enclosed in curly braces.
Consist of key-value pairs.

In [ ]:
months = {'Jan': 31, 'Feb': 28, 'Mar': 31, 'Apr': 30, 'May':31, 'Jun':30, 'Jul':31}

print(f'Dictionary: {months} and data type : {type(months)}')

dict1 = {} #initalize dictionary object as dict1

dict1['one'] = 'This is one.'  #Here key is 'one' and value is 'This is one'.
dict1['two'] = 'This is two.'
dict1['three'] = 'This is three.'

print(dict1['one']) 

print(f'All the values of dict1 :{dict1.values()}') #print all the values 
print(f'All the keys of dict1 :{dict1.keys()}') #print all the keys


Dictionary: {'Jan': 31, 'Feb': 28, 'Mar': 31, 'Apr': 30, 'May': 31, 'Jun': 30, 'Jul': 31} and data type : <class 'dict'>
This is one.
print all the values of dict1 :dict_values(['This is one.', 'This is two.', 'This is three.'])
print all the keys of dict1 :dict_keys(['one', 'two', 'three'])


# Dicision Making

1. if statement
2. if else statment
3. elif statement

**if statement**

In [ ]:
var1 = 100

if var1:
  print('1 : Got a true expression value')
  print(var1)

var2 = 0
if var2:
  print('2 : Got a true expression')
  print(var2)
print('Good bye!')

1 : Got a true expression value
100
Good bye!


**if else statement**

In [ ]:
num12 = 11
if num12 < 13:
  print(f'{num12} is less than 13.')

else:
  print(f'{num12} is greater than 13.')


11 is less than 13.


**elif statement**

In [ ]:
num12 = 15
if num12 < 13:
  print(f'{num12} is less than 13.')

elif num12 < 20:
  print(f'{num12} is less than 20.')

else:
  print(f'{num12} is greater than 20.')


15 is less than 20.


# Loop construction

1. While loop
2. For loop
3. Use else with while loop
4. Range function
5. Enumerate



**1. While loop** --> Iterate over a block of code as long as the test expression is true.

In [ ]:
count = 0
while (count < 5):
  print(f'This count is: {count}')
  count = count + 1
print('Good bye!')

This count is: 0
This count is: 1
This count is: 2
This count is: 3
This count is: 4
Good bye!


**2. For loop** --> Iterate over a sequence (list, tuple, dictionary, string).

In [ ]:
for count in range(5):
  print(f'This count is: {count}')

This count is: 0
This count is: 1
This count is: 2
This count is: 3
This count is: 4


**3. Else with while loop**

In [ ]:
count = 0
while count < 5:
  print(f'{count} is less than 5')
  count = count + 1
else:
  print(f'{count} is not less than 5')


0 is less than 5
1 is less than 5
2 is less than 5
3 is less than 5
4 is less than 5
5 is not less than 5


**4. Range** --> Generate an iterator to progress integers starting with **a** to **n-1**.

In [ ]:
a = 3
b = 10

gap = 2

print(f'List with range of {a} and {b-1} :{list(range(a,b))}')

print(f'List with range of {a} and {b-1} with gap of {gap} :{list(range(a,b,gap))}')

print(f'List with range starting from 0 to and {b-1} :{list(range(a,b))}')    # print the value starting from 0 to b-1.

List with range of 3 and 9 :[3, 4, 5, 6, 7, 8, 9]
List with range of 3 and 9 with gap of 2 :[3, 5, 7, 9]
List with range starting from 0 to and 9 :[3, 4, 5, 6, 7, 8, 9]


**5. Enumerate** --> When we required values with iterator, Enumerate is used.

In [ ]:
mylist12 = ['This','boy','is','my','son']

print(list(enumerate(mylist12)))

for count, values in enumerate(mylist12,5):#2nd parameter can be started from user defined value
   print(count, values)


[(0, 'This'), (1, 'boy'), (2, 'is'), (3, 'my'), (4, 'son')]
5 This
6 boy
7 is
8 my
9 son


# Reading and Writing Files

**1. Opening a file in read mode**




In [ ]:
# Connecting to google drive
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
path = '/content/gdrive/MyDrive/FDP_NLP/'

fobj = open(path+'sample.txt','r') 
for line in fobj:
  print(line.rstrip())

fobj.close()

**2. Writing a file**

In [ ]:
fh = open(path +'write_sample.txt','w')
fh.write('This sentence is written sentence \n by using the write function')
fh.close()

with open(path+'write_sample.txt','w') as fh:
  fh.write('This is second sentence written in file by using the write function')

**3. Simulataneous Read and Write**

In [ ]:
fobj_in = open(path+'sample.txt')
fobj_out = open(path+'sample_copy.txt','w')
i = 1
for line in fobj_in:
  print(line.rstrip())
  fobj_out.write(str(i) + ":" + line)  #don't rstrip line while writing
  i = i+1
fobj_in.close()
fobj_out.close()

Roses are red, sky is blue.
Sugar is sweet, and so are you.


**4. Reading file in one go**

In [ ]:
sample = open(path+'write_sample.txt').readlines()
print(sample)

['This is second sentence written in file \n', ' by using the write function']


**5. Reading CSV file**

In [ ]:
import csv
with open(path+'example.csv') as csvfile:
  readcsv = csv.reader(csvfile,delimiter=',')
  for row in readcsv:
    print(row)

['1/2/2022', '5', '8', 'red']
['1/1/2021', '5', '2', 'green']
['10/1/2022', '9', '1', 'blue']


**6. CSV writer**

In [ ]:
import csv
nms = [[1,2,3],[4,5,6],[7,8,9],[11,12,13]]
f = open(path+'sample2.csv','w',newline = '')
with f:
  writer = csv.writer(f)
  for row in nms:
    print(row)
    writer.writerow(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
[11, 12, 13]


# Numpy

**Numpy** is the fundamental package for scientific computing with python.

In [ ]:
import numpy as np

myarray = np.array([4,3,2])
print(f'myarray: {myarray} and data type is {type(myarray)}')

float_data = np.array([4,3,2],dtype = float)
print(f'float_data: {float_data} and data type is {type(float_data)}')

#Creating n-numbers of similar object
print(f'List of 1 of size 3 :{np.ones(3)}')

print(f'Multi dimension list of zeros of size :{np.zeros((2,4))}')

myarray: [4 3 2] and data type is <class 'numpy.ndarray'>
float_data: [4. 3. 2.] and data type is <class 'numpy.ndarray'>
List of 1 of size 3 :[1. 1. 1.]
Multi dimension list of zeros of size :[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Operation in Numpy**

In [ ]:
a = np.arange(10).reshape(5,2) #arange function create sequence

print(f'Numpy array a :{a}')

print(f'size of numpy array a :{np.size(a)}')

print(f'shape of numpy array a :{np.shape(a)}')

print(f'Reshaped of numpy array a :{np.reshape(a,(2,5))}')

print(f'Numpy array a to 1-d :{np.ravel(a)}')

print(f'transpose of numpy array a :{np.transpose(a)}')

print(f' Return the index with values less than 5: {np.where(a<5)}') #Return the index where a <5

print(f' Return values less than 5 :{a[np.where(a<5)]}') #Return values a<5


Numpy array a :[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
size of numpy array a :10
shape of numpy array a :(5, 2)
Reshaped of numpy array a :[[0 1 2 3 4]
 [5 6 7 8 9]]
Numpy array a to 1-d :[0 1 2 3 4 5 6 7 8 9]
transpose of numpy array a :[[0 2 4 6 8]
 [1 3 5 7 9]]
 Return the index with values less than 5: (array([0, 0, 1, 1, 2]), array([0, 1, 0, 1, 0]))
 Return values less than 5 :[0 1 2 3 4]


# Pandas
Python package offers various data structures and operations for numerical and time series data.

In [ ]:
import pandas as pd

dataframe = pd.read_csv(path+'employee.csv')
dataframe.head()

Name  Age Address
0    Ajay   25  Kanpur
1  Vikash   26   Patna
2  Gaurav   29   Delhi
3   Yadav   28   Bihar
4  Ashish   32   Patna

In [ ]:
import pandas as pd  #importing pandas package

data = {'Name':['Ajay','Vikash','Gaurav','Yadav'],
        'Age':[25, 26, 29, 28],
        'Address':['Kanpur','Patna','Delhi','Bihar']}

df1 = pd.DataFrame(data)  #Converting dictionary into dataframe

df1.to_csv(path+'employee_data.csv',sep=',',index = False ) # Saving dataframe as csv file

print(df1)

     Name  Age Address
0    Ajay   25  Kanpur
1  Vikash   26   Patna
2  Gaurav   29   Delhi
3   Yadav   28   Bihar


In [ ]:
data2 = {'Qualification':['BSc','M.Tech','M.Tech','MCA']}

df2 = pd.DataFrame(data2)  #Converting dictionary into dataframe

final_df = pd.concat([df1, df2], axis=1) #Concatenating the two dataframe

print(final_df)

     Name  Age Address Qualification
0    Ajay   25  Kanpur           BSc
1  Vikash   26   Patna        M.Tech
2  Gaurav   29   Delhi        M.Tech
3   Yadav   28   Bihar           MCA


In [ ]:
final_df['Address']= final_df['Address'].str.upper()  #Coverting and overwriting values in column
print(final_df)

     Name  Age Address Qualification
0    Ajay   25  KANPUR           BSc
1  Vikash   26   PATNA        M.Tech
2  Gaurav   29   DELHI        M.Tech
3   Yadav   28   BIHAR           MCA


In [ ]:
temp_df = final_df['Qualification'].copy()  #making copy of Qualification column

final_df['Name']= final_df['Name'].str.cat(temp_df, sep =", ") #concatenating qualification with name

print(final_df)

             Name  Age Address Qualification
0       Ajay, BSc   25  KANPUR           BSc
1  Vikash, M.Tech   26   PATNA        M.Tech
2  Gaurav, M.Tech   29   DELHI        M.Tech
3      Yadav, MCA   28   BIHAR           MCA


In [ ]:
 #Data
import pandas as pd
import numpy as np

nan_data = pd.DataFrame({"A":[12, 4, 5, None, 1], 
                   "B":[None, 2, 54, 3, np.nan], 
                   "C":[20, 16, 43, 3, 8], 
                   "D":[14, 3, None, np.nan, 6]}) 

print(nan_data)

      A     B   C     D
0  12.0   NaN  20  14.0
1   4.0   2.0  16   3.0
2   5.0  54.0  43   NaN
3   NaN   3.0   3   NaN
4   1.0   NaN   8   6.0


In [ ]:
data_nan = nan_data.dropna()  #Removing the row having atleast single nan value
print(data_nan)

     A    B   C    D
1  4.0  2.0  16  3.0


In [ ]:
fill_nan = nan_data.fillna(0)  #Filling all the nan value with zeros
print(fill_nan)

      A     B   C     D
0  12.0   0.0  20  14.0
1   4.0   2.0  16   3.0
2   5.0  54.0  43   0.0
3   0.0   3.0   3   0.0
4   1.0   0.0   8   6.0
